Add default reviewers (#23)
* Add expected behaviours as tests first for the new feature

* Fall back to the default reviewers when no reviewers are matched

* Update README and bump minor version

* Address lint errors

* Get CI to fail if npm run build isn't run yet

* Update dist

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,6 +26,13 @@ jobs:
     - name: Install dependencies
       run: npm install
 
+    - name: Check if dist is updated
+      run: |
+        npm run build
+        set -e # exit immediatel if a command below returns a non-zero status
+        git status # display the reuslts for debugging
+        test -z "$(git status --porcelain)"
+
     - name: Run linter and tests
       run: |
         npm run lint
